language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

script:
    - vendor/bin/tester -i -p php
    - vendor/bin/tester tests/Uniparser -s -p php

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

before_script:
    # Update Composer
    - composer self-update

    # Install Nette Tester
    - composer install --no-interaction --prefer-source
